### ISSUE TITLE
list-style

### ISSUE THREAD

**Issue by brenna** [tedconf/shed-css#14]
Came across a use case for ~~`list-style: none`~~ `list-style-type: none`.
 
Consider including `none` and a couple other sane defaults:
* `none`
* `disc`
* `circle`
* `square`
* `decimal`
* `lower-roman`
* `lower-latin`

Exhaustive list here: https://www.w3.org/wiki/CSS/Properties/list-style-type#Values

Thoughts @tedconf/frontenders ?

**Comment by VinSpee** [comment]
I think that'd be 

`l-s-t`, which is the most specific (`list-style-type`). I have been handling this in a reset thus far but am happy to have it in there

**Comment by brenna** [comment]
Ah yeah good call on `l-s-t`. What do you think about the types to include?

**Comment by VinSpee** [comment]
it'd also be good to have some of the `ul` related items too, disc, square, etc

**Comment by brenna** [comment]
Good call, updated the list above.

**Comment by VinSpee** [comment]
i dig it. wanna PR and i can cut a release or walk you through cutting one?

**Comment by brenna** [comment]
yes and yes.
