### ISSUE TITLE
unable to build on fresh repo clone

### ISSUE THREAD

**Issue by brenna** [tedconf/shed-css#16]
The `lib` folder is ignored in git, so it arrives empty when cloning the repo.  The build will fail unless  the `lib/index.css` and `lib/generate-theme.scss` files present.

Build scripts should check for file presence and create the files if not there before attempting to operate on them.... or some other workaround if you can think of one, @VinSpee

**Comment by VinSpee** [comment]
i really want to avoid this being a `postinstall` as that would trigger a build after a consumer npm installs, I'll try to think on a workaround.

**Comment by brenna** [comment]
oops, didn't think of that. I'm sure this could be integrated elsewhere in the scripts.

**Comment by VinSpee** [comment]
what if I just commit these files?

**Comment by brenna** [comment]
I'd say fine with me...as long as that won't result in crappy merge conflicts all the time.  

I can also take a closer look at the npm script hooks.
