### ISSUE TITLE
box-shadow

### ISSUE THREAD

**Issue by MarkPerryBV** [tedconf/shed-css#20]
Any plans to add box-shadow classes to the library?

Wanted to make some Material Design looking elements but no native shadow styles available.

**Comment by VinSpee** [comment]
I’d certainly consider it. The trick is balancing covering common use cases with flexibility. How do you InVision the syntax? Something simple like:

`b-s:1`

Where `1` is a measure of “depth”?

Or something more complex?

**Comment by MarkPerryBV** [comment]
Pretty much. I don't need anything more complex. Other "Atomic" CSS frameworks have support for it.

I can add it to my own CSS though if aren't sold on it. Just with the rise of Material style UI I thought it would be a nice addition.

**Comment by VinSpee** [comment]
I chatted about this with some of the team.

I think this is _a bit_ too stylistically opinionated to make it to core. However, I understand the value and need. Here's what I think an independent module would look like:

https://codepen.io/VinSpee/pen/OxMMbg?editors=1100

**Comment by VinSpee** [comment]
@MarkPerryBV does that suffice?
