### ISSUE TITLE
How do i use breakpoint?

### ISSUE THREAD

**Issue by muhajirframe** [tedconf/shed-css#21]
Do we have something like `padding:5-md` For mq min width medium?

**Comment by muhajirframe** [comment]
Ah, I found it , we use classname@mq right. But it's not well documented yet.

**Comment by VinSpee** [comment]
@muhajirframe thanks for noting that it wasn't in the docs. I added a section here: http://tedconf.github.io/shed-css/docs.html#media-queries

feel free to open other issues for additional questions!
