### ISSUE TITLE
cursor

### ISSUE THREAD

**Issue by VinSpee** [tedconf/shed-css#3]
we need cursor helpers!
## Properties

- `auto`
- `default`
- `none`
- `context-menu`
- `help`
- `pointer`
- `progress`
- `wait`
- `cell`
- `crosshair`
- `text`
- `vertical-text`
- `alias`
- `copy`
- `move`
- `no-drop`
- `not-allowed`
- `e-resize`
- `n-resize`
- `ne-resize`
- `nw-resize`
- `s-resize`
- `se-resize`
- `sw-resize`
- `w-resize`
- `ew-resize`
- `ns-resize`
- `nesw-resize`
- `nwse-resize`
- `col-resize`
- `row-resize`
- `all-scroll`
- `zoom-in`
- `zoom-out`
- `grab`
- `grabbing`

we could probably start with a subset of these.

**Comment by than** [comment]
- [ ] `auto`
- [ ] `default`
- [ ] `none`
- [ ] `context-menu`
- [ ] `help`
- [ ] `pointer`
- [ ] `progress`
- [ ] `wait`
- [ ] `cell`
- [ ] `crosshair`
- [ ] `text`
- [ ] `vertical-text`
- [ ] `alias`
- [ ] `copy`
- [ ] `move`
- [ ] `no-drop`
- [ ] `not-allowed`
- [ ] `e-resize`
- [ ] `n-resize`
- [ ] `ne-resize`
- [ ] `nw-resize`
- [ ] `s-resize`
- [ ] `se-resize`
- [ ] `sw-resize`
- [ ] `w-resize`
- [ ] `ew-resize`
- [ ] `ns-resize`
- [ ] `nesw-resize`
- [ ] `nwse-resize`
- [ ] `col-resize`
- [ ] `row-resize`
- [ ] `all-scroll`
- [ ] `zoom-in`
- [ ] `zoom-out`
- [ ] `grab`
- [ ] `grabbing`

**Comment by than** [comment]
@VinSpee I plucked out what felt like the handiest subset of cursors here.

**Comment by brenna** [comment]
`default`, `none` and `not-allowed` are about all i use

**Comment by VinSpee** [comment]
released in `1.2.0`
